services:

# MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db


# Node API service
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGO_URL: "mongodb+srv://Jill:Jill123@cluster0.jqqjgcc.mongodb.net/SMS"
      # MONGO_URL: "mongodb://host.docker.internal:27017/SMS"
    depends_on:
      - mongo_db
  
volumes:
  mongo_db: {}
  